baseURL = "https://mpw.netlify.com/"
languageCode = "en-us"
title = "Můj Programovací Web"
pluralizelisttitles = "false"

    
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5