baseURL = "https://programovaciweb.tk/"
title = "Můj Programovací Web"
pluralizelisttitles = "false"
author = "Lukáš Kovář"
description = "Web kde sdílím svoje projekty. Většina výtvorů je zde vytvořena za pomocí JavaScriptu a používám framework P5.JS"
languageCode = "cs-CZ"
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-144365131-1"
disqusShortname = "muj-programovaci-web"

[permalinks]
    post = "/projekty/:title/"
    
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
