version: "3.7"

services:
  server:
    image: klakegg/hugo:0.56.0
    command: server
    volumes:
      - .:/src
    ports:
      - 1313:1313
  build:
    image: klakegg/hugo:0.64.1
    volumes:
      - .:/src
      - ./output:/target
