backend:
  name: github
  repo: sirluky/MujProgramovaciWeb

public_folder: 'images/'

media_folder: 'static/images/'

collections:
  - name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label: 'Projekty' # Used in the UI
    folder: 'content/projekty/' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Titulek', name: 'title', widget: 'string' }
      - { label: 'Popisek', name: 'desc', widget: 'string' }
      - { label: 'Tagy', name: 'tags', widget: 'list', required: false }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Náhledový obrázek', name: 'thub', widget: 'image', required: false }
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
      - { label: 'Knihovny', name: 'libs', widget: 'list', required: false }
      - { label: 'Redirect', name: 'redirect', widget: 'string', required: false }
      - { label: 'Podpora mobilního zobrazení', name: 'mobile', widget: 'boolean', default: false, required: false }
      - { label: 'Scroll Lock', name: 'scroll', widget: 'boolean', default: false, required: false }

  - name: 'Iframed' # Used in routes, e.g., /admin/collections/blog
    label: 'Iframed projekty' # Used in the UI
    folder: 'content/projektfull/' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Titulek', name: 'title', widget: 'string' }
      - { label: 'Popisek', name: 'desc', widget: 'string', required: false }
      - { label: 'Tagy', name: 'tags', widget: 'list', required: false }
      - { label: 'Datum', name: 'date', widget: 'datetime', required: false }
      - { label: 'Náhledový obrázek', name: 'thub', widget: 'image', required: false }
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
      - { label: 'Knihovny', name: 'libs', widget: 'list', required: false }
  - name: 'technologie' # Used in routes, e.g., /admin/collections/blog
    label: 'Technologie' # Used in the UI
    folder: 'content/technologie/' # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Titulek', name: 'title', widget: 'string' }
      - { label: 'Popisek', name: 'desc', widget: 'string', required: false }
      - { label: 'Tagy', name: 'tags', widget: 'list', required: false }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
      - { label: 'Knihovny', name: 'libs', widget: 'list', required: false }
      - { label: 'URL', name: 'link', widget: 'string', required: false }
