backend:
  name: git-gateway
  branch: master

public_folder: 'static/images/'

media_folder: 'static/images/'

collections:
  - name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label: 'Projekty' # Used in the UI
    folder: 'content/projekty/' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Titulek', name: 'title', widget: 'string' }
      - { label: 'Popisek', name: 'desc', widget: 'string' }
      - { label: 'Tagy', name: 'tags', widget: 'string', required: false }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Náhledový obrázek', name: 'cover', widget: 'image', required: false }
      # - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
